# **Data Cleaning**
Avi Bauer & Matthew Duffy

In [ ]:
# Step 0: import libraries

import os
import pandas as pd

## **Step 1: Convert data files from Google Drive.**
This section is adapted from code provided in class: `convert_dta_to_csv (colab version).ipynb`

In [ ]:
# Step 1.1: access Google Drive.

# import requisite library
from google.colab import drive

# login and verity that you want to use it
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Step 1.2: Move us to the "Data" folder

# identify the root directory
root_dir = "/content/drive/My Drive/"

# identify the location of the data folder
data_folder = root_dir + "Data - Human Centered DS"

# change directory to the data folder
os.chdir(data_folder)

In [ ]:
# Step 1.3.1: Define "dta_to_csv()"
# (this is a helper function to "convert_all_dta_to_csv()")

# store new csv files in subdirectory "/csv"
# also creates a populated list of all our new shiny csv file locations

def dta_to_csv(dta_file_path,name_list,save_files):
  """
  takes a path to a .dta file and converts it to a .csv. The result
  is stored a subdirectory of the original directory named "/csv".

  Arguments:
    dta_file_path: Full path to the .dta file
    name_list: A list to store path as a string
    save_files: Boolean, whether to create new .csv files (True) or not (False)

  """

  # get the directory and file name from the full path
  # reconstitute into a new filepath for output
  directory_name, file_name = os.path.split(dta_file_path)
  output_path = f'{directory_name}/csv/{os.path.splitext(file_name)[0]}.csv'

  # save output_path to name_list for future reference
  name_list.append(output_path)

  # check if save_files = True
  if save_files:

    # read the .dta file into a DataFrame
    print("Converting file", dta_file_path)
    print("Output location", output_path)
    data = pd.io.stata.read_stata(dta_file_path)

    # save the DataFrame as a ".csv" to the "csv" directory in the original path (output_path)
    data.to_csv(output_path)

# end data_to_csv()

# - - - - - - -

# Step 1.3.2: Define "convert_all_dta_to_csv()"

def convert_all_dta_to_csv(data_folder,name_list,save_files):
  """
  Traverse the directory that has path name data_folder. Look for
  .dta files and call dta_to_csv() to convert them to .csv
  """

  # Walk the directory structure
  for root, direc, files in os.walk(data_folder):
    for file in files:
      file_path = os.path.join(root, file)

      # split the file into its name and extension
      filename, extension = os.path.splitext(file)

      # does the file have a .dta extension
      if extension.lower() == ('.dta'):
        dir_path = root # store current directory

        # Create a 'csv' subdirectory if it doesn't exist
        csv_dir_path = os.path.join(dir_path, 'csv')
        if not os.path.exists(csv_dir_path):
          os.makedirs(csv_dir_path)

        # call the conversion function
        dta_to_csv(file_path,name_list,save_files)

# end convert_all_dta_to_csv()

In [ ]:
# Step 1.4: call the 2nd function to do the conversion and save the files

# CALL THIS CELL ONLY ONCE! THIS MAKES NEW FILES!!!

# initiate an empty list and pass it and the data_folder location to our function
path_list = []
convert_all_dta_to_csv(data_folder,path_list,True)

Converting file /content/drive/My Drive/Data - Human Centered DS/Randomization and heterogeneity.dta
Output location /content/drive/My Drive/Data - Human Centered DS/csv/Randomization and heterogeneity.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/User survey/user survey_endline data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/User survey/csv/user survey_endline data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Admin/admin_long data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Admin/csv/admin_long data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Admin/admin_wide data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Admin/csv/admin_wide data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Police survey/police_baseline data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Police survey/csv/police_baseline data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Police survey/police_station personnel data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Police survey/csv/police_station personnel data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Police survey/police_full data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Police survey/csv/police_full data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/CCTV/cctv_baseline data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/CCTV/csv/cctv_baseline data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/CCTV/cctv_full data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/CCTV/csv/cctv_full data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Citizen survey/citizen_full data.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Citizen survey/csv/citizen_full data.csv
Converting file /content/drive/My Drive/Data - Human Centered DS/Citizen survey/citizen_caw rates.dta
Output location /content/drive/My Drive/Data - Human Centered DS/Citizen survey/csv/citizen_caw rates.csv

In [ ]:
# Step 1.5: Generate a list of path names

# CALL THIS CELL ONLY IF YOU SKIP STEP 1.4
# THIS CELL DOES *NOT* CREATE NEW FILES, JUST GATHERS PATHS

# initiate an empty list and pass it and the data_folder location to our function
# but do not save any new .csv files
path_list = []
convert_all_dta_to_csv(data_folder,path_list,False) # flag "save_files" as False

## **Step 2: Read our data files of interest into pandas dataframes.**

In [ ]:
# Step 2.1: Make a list of suitable df names

# initialize an empty list
file_list = []

# iterate through path_list
for path_name in path_list:

  # split the path to get file_name
  directory_name, file_name = os.path.split(path_name)

  # drop .csv and remove spaces or uppercase
  file_name = os.path.splitext(file_name)[0]
  file_name = file_name.replace(' ','_').lower()

  # append to file_list
  file_list.append(file_name)

# sanity check: display the new file names
display(file_list)

['randomization_and_heterogeneity',
 'user_survey_endline_data',
 'admin_long_data',
 'admin_wide_data',
 'police_baseline_data',
 'police_station_personnel_data',
 'police_full_data',
 'cctv_baseline_data',
 'cctv_full_data',
 'citizen_full_data',
 'citizen_caw_rates']

In [ ]:
#data_dic['police_station_personnel_data'].info()
#data_dic['admin_long_data'].info()
#x = pd.merge(data_dic['police_station_personnel_data'],data_dic['admin_long_data'], how='left', on='ps_code')

In [ ]:
import seaborn as sns
# sns.scatter()

In [ ]:
# Step 2.2: Read our CSV files and store w/ correct keys in a dictionary

# initiate an empty dictionary
data_dic = {}

# iterate through file_list (and, by extension, the paired list path_list)
for i, file_name in enumerate(file_list):

  # debugging: print paths and file names
  # print("Path:",path_list[i])
  # print("File:",file_name)

  # add a new key:value pair to data_dic:
  # key = file_name = file_list[i]
  # value = path_list[i] read to df
  data_dic[file_name] = pd.read_csv(path_list[i])

# debugging: display one df to confirm correct naming and placement
display(data_dic['citizen_caw_rates'])

,Unnamed: 0,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,b_caw_rate,e_caw_rate
0,0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,0.038462,0.000000
1,1,1002.0,170000,Rural,1.0,-0.960574,Control,control,1000.0,NaN,1.545454,NaN,0.0,0.0,0.038462,0.114887
2,2,1003.0,102467,Rural,1.0,1.042663,Control,control,1000.0,NaN,1.090909,NaN,0.0,0.0,0.083333,0.043200
3,3,1004.0,54000,Rural,1.0,-1.590761,Treatment,regular mhd,1000.0,7.0,3.897297,2.03,1.0,0.0,0.000000,0.000000
4,4,1005.0,76376,Rural,1.0,-1.570695,Treatment,women officers,1000.0,9.0,4.157658,2.20,0.0,1.0,0.192308,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,12176.0,23565,Rural,18.0,-1.401651,Control,control,12000.0,NaN,1.363636,NaN,0.0,0.0,0.000000,0.060906
176,176,12177.0,151916,Rural,18.0,-0.794338,Treatment,regular mhd,12000.0,7.0,2.911111,2.16,1.0,0.0,0.000000,0.000000
177,177,12178.0,70000,Rural,18.0,-1.830616,Control,control,12000.0,NaN,0.000000,NaN,0.0,0.0,0.063830,0.000000
178,178,12179.0,165000,Rural,18.0,0.386970,Treatment,women officers,12000.0,9.0,3.890601,3.21,0.0,1.0,0.000000,0.000000
179,179,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,0.062500,0.024804

## **Step 3: Clean our files of interest.**

Needed for Question 1:

*   police_full_data
*   police_station_personnel_data
*   randomization_and_heterogeneity

Needed for Question 2:

*   admin_wide_data
*   citizen_full_data
*   randomization_and_heterogeneity

Needed for Question 3:

*   citizen_full_data
*   user_survey_endline_data
*   randomization_and_heterogeneity

Needed for Question 4:

*   admin_long_data
*   police_station_personnel_data
*   cctv_full_data
*   randomization_and_heterogeneity

Overall:

*   randomization_and_heterogeneity (x4)
*   police_station_personnel_data (x2)
*   admin_long_data
*   admin_wide_data
*   citizen_full_data (x2)
*   police_full_data
*   user_survey_endline_data
*   cctv_full_data

In [ ]:
#Display keys to dataframes
data_dic.keys()

dict_keys(['randomization_and_heterogeneity', 'user_survey_endline_data', 'admin_long_data', 'admin_wide_data', 'police_baseline_data', 'police_station_personnel_data', 'police_full_data', 'cctv_baseline_data', 'cctv_full_data', 'citizen_full_data', 'citizen_caw_rates'])

### Step 3.1: Clean `randomization_and_heterogeneity`

In [ ]:
# Step 3.1.1: isolate just the df we need

# assign df to a variable
random_df = data_dic['randomization_and_heterogeneity']

# take a look
random_df.head(10)

,Unnamed: 0,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,0,47,412,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0
1,1,29,218,170000,Rural,1.0,-0.960574,Control,control,1000.0,NaN,1.545454,NaN,0.0,0.0
2,2,75,694,102467,Rural,1.0,1.042663,Control,control,1000.0,NaN,1.090909,NaN,0.0,0.0
3,3,40,144,54000,Rural,1.0,-1.590761,Treatment,regular mhd,1000.0,7.0,3.897297,2.03,1.0,0.0
4,4,37,130,76376,Rural,1.0,-1.570695,Treatment,women officers,1000.0,9.0,4.157658,2.20,0.0,1.0
5,5,30,263,77961,Rural,1.0,-1.324667,Treatment,women officers,1000.0,9.0,3.973856,2.31,0.0,1.0
6,6,64,536,277108,Rural,1.0,1.325031,Control,control,1000.0,NaN,1.166667,NaN,0.0,0.0
7,7,25,52,69600,Rural,1.0,-2.095523,Control,control,1000.0,NaN,1.400000,NaN,0.0,0.0
8,8,43,365,190572,Rural,1.0,-0.113645,Treatment,regular mhd,1000.0,5.0,1.553922,0.00,1.0,0.0
9,9,31,160,84450,Rural,1.0,-1.567298,Treatment,regular mhd,1000.0,9.0,3.765504,2.15,1.0,0.0

In [ ]:
# Step 3.1.2: Do some initial exploring around Null data

# get some basic information from info()
random_df.info()

# from this we see:
# there are Null values in 2 columns: [implement_quality, comm_outreach_strength]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               180 non-null    int64
 1   total_assigned_officers  180 non-null    int64
 2   total_fir_2017           180 non-null    int64
 3   population               180 non-null    int64
 4   urban                    180 non-null    object
 5   dist_urban               180 non-null    float64
 6   strat_pca                180 non-null    float64
 7   treatment                180 non-null    object
 8   group                    180 non-null    object
 9   dist_id                  180 non-null    float64
 10  implement_quality        119 non-null    float64
 11  training_score           180 non-null    float64
 12  comm_outreach_strength   119 non-null    float64
 13  regular_whd              180 non-null    float64
 14  women_whd                180 non-null    float64
dtypes: float64(8), int64(4), object(3)
memory usage: 21.2+ KB

In [ ]:
# Question: do these null values in the two columns coincide, as they each contain 119 valid values?

# find all rows where either are null
double_null = random_df[random_df['comm_outreach_strength'].isna() | random_df['implement_quality'].isna()]

# find all rows where just implement_quality is null
implement_null = random_df[random_df['comm_outreach_strength'].notna() & random_df['implement_quality'].isna()]

# find all rows where just comm_outreach_strength is null
comm_null = random_df[random_df['comm_outreach_strength'].isna() & random_df['implement_quality'].notna()]

print("Doubles:",len(double_null)) # Doubles: 61
print("Implementation Only:",len(implement_null)) # Implementation Only: 0
print("Community Only:",len(comm_null)) # Community Only: 0

# Answer: yes, we have 61 cases where both are dropped,
# and no cases where only one was dropped.

Doubles: 61
Implementation Only: 0
Community Only: 0

In [ ]:
# 61 is almost perfectly 1/3 of the 180 entries
# Hypothesis: these are the control group

# grab just our control group and check for not-null values from this subset
random_df_control = random_df[random_df['treatment'] == "Control"]
# random_df_control.notna().sum() # UNCOMMENT TO RUN
# RESULT: 60 entries, 0 non-null values in our two problem columns

# subquestion: where's #61?

# grab the remainder and check for not-null values
random_df_treatment = random_df[random_df['treatment'] != "Control"]
# random_df_treatment.notna().sum() # UNCOMMENT TO RUN
# RESULT: 120 entries, 1 missing value in each problem column

# find our problem row
random_df_problem = random_df[(random_df['treatment'] != "Control") & random_df['implement_quality'].isna()]
display(random_df_problem)

,Unnamed: 0,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
19,19,50,104,125000,Rural,2.0,-1.092783,Treatment,regular mhd,2000.0,NaN,0.727273,NaN,1.0,0.0

In [ ]:
# For now, let's sub in the mean value for each of our problem columns
for col in ['implement_quality','comm_outreach_strength']:
  random_df[col] = random_df[col].fillna(random_df[col].mean())

In [ ]:
# Step 3.1.3: Check and clean up data types

# get some basic information from info() again
random_df.info()

# COLUMNS OF INTEREST:
# dist_urban might be better as int - worth checking
# dist_id, regular_whd, women_whd should definitely be int

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               180 non-null    int64
 1   total_assigned_officers  180 non-null    int64
 2   total_fir_2017           180 non-null    int64
 3   population               180 non-null    int64
 4   urban                    180 non-null    object
 5   dist_urban               180 non-null    float64
 6   strat_pca                180 non-null    float64
 7   treatment                180 non-null    object
 8   group                    180 non-null    object
 9   dist_id                  180 non-null    float64
 10  implement_quality        180 non-null    float64
 11  training_score           180 non-null    float64
 12  comm_outreach_strength   180 non-null    float64
 13  regular_whd              180 non-null    float64
 14  women_whd                180 non-null    float64
dtypes: float64(8), int64(4), object(3)
memory usage: 21.2+ KB

In [ ]:
# check the values in dist_urban via .value_counts()
random_df['dist_urban'].value_counts()

# Conclusion: dist_urban should be integers as well

dist_urban
4.0     22
8.0     20
6.0     17
10.0    15
2.0     12
1.0     10
17.0    10
11.0    10
9.0     10
18.0    10
15.0     9
5.0      8
12.0     8
13.0     7
7.0      5
14.0     3
3.0      3
16.0     1
Name: count, dtype: int64

In [ ]:
# convert selected float columns to int
random_df = random_df.astype({'dist_urban':'int','dist_id':'int','regular_whd':'int','women_whd':'int'})

# also let's rename that first column to rand_index
random_df = random_df.rename(columns={'Unnamed: 0':'rand_index'})

# check our work and we're done!
random_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rand_index               180 non-null    int64
 1   total_assigned_officers  180 non-null    int64
 2   total_fir_2017           180 non-null    int64
 3   population               180 non-null    int64
 4   urban                    180 non-null    object
 5   dist_urban               180 non-null    int64
 6   strat_pca                180 non-null    float64
 7   treatment                180 non-null    object
 8   group                    180 non-null    object
 9   dist_id                  180 non-null    int64
 10  implement_quality        180 non-null    float64
 11  training_score           180 non-null    float64
 12  comm_outreach_strength   180 non-null    float64
 13  regular_whd              180 non-null    int64
 14  women_whd                180 non-null    int64
dtypes: float64(4), int64(8), object(3)
memory usage: 21.2+ KB

### Step 3.2: Clean `police_station_personnel_data`

In [ ]:
# Step 3.2.1: isolate just the df we need

# assign to a variable
psp_df = data_dic['police_station_personnel_data']

# take a look
psp_df.head(10)

,Unnamed: 0,e_total_surveyed,e_female_surveyed,e_male_surveyed,ps_code,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,...,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,e_male_weight,b_male_weight,e_female_weight,b_female_weight
0,0,12.0,1.0,11.0,1001.0,48.0,6.0,11.0,1.0,42.0,...,1000.0,9.0,2.916667,2.20,0.0,1.0,3.818182,3.272727,6.000000,3.000000
1,1,11.0,0.0,11.0,1002.0,29.0,2.0,6.0,0.0,27.0,...,1000.0,NaN,1.545454,NaN,0.0,0.0,2.454546,1.727273,NaN,1.000000
2,2,11.0,1.0,10.0,1003.0,79.0,6.0,13.0,2.0,73.0,...,1000.0,NaN,1.090909,NaN,0.0,0.0,7.300000,4.900000,3.000000,3.500000
3,3,10.0,2.0,8.0,1004.0,33.0,3.0,7.0,1.0,30.0,...,1000.0,7.0,3.897297,2.03,1.0,0.0,3.000000,1.800000,1.000000,1.333333
4,4,12.0,3.0,9.0,1005.0,32.0,7.0,4.0,2.0,25.0,...,1000.0,9.0,4.157658,2.20,0.0,1.0,2.777778,2.500000,2.333333,1.500000
5,5,9.0,3.0,6.0,1006.0,34.0,3.0,6.0,1.0,31.0,...,1000.0,9.0,3.973856,2.31,0.0,1.0,3.100000,1.900000,1.000000,1.000000
6,6,12.0,2.0,10.0,1007.0,62.0,8.0,11.0,1.0,54.0,...,1000.0,NaN,1.166667,NaN,0.0,0.0,5.400000,5.500000,4.000000,2.000000
7,7,10.0,1.0,9.0,1008.0,19.0,2.0,3.0,0.0,17.0,...,1000.0,NaN,1.400000,NaN,0.0,0.0,1.888889,1.666667,1.000000,1.500000
8,8,12.0,2.0,10.0,1009.0,69.0,7.0,15.0,1.0,62.0,...,1000.0,5.0,1.553922,0.00,1.0,0.0,6.200000,4.400000,3.500000,2.500000
9,9,12.0,1.0,11.0,1010.0,35.0,4.0,7.0,2.0,31.0,...,1000.0,9.0,3.765504,2.15,1.0,0.0,2.818182,2.545454,4.000000,2.000000

In [ ]:
# Check for nulls
psp_df.isna().sum()

Unnamed: 0                 0
e_total_surveyed           0
e_female_surveyed          0
e_male_surveyed            0
ps_code                    0
e_total_staff              0
e_female_staff             0
e_total_officers           0
e_female_officers          0
e_male_staff               0
e_male_officers            0
e_female_sho               0
b_total_staff              0
b_female_staff             0
b_male_staff               0
b_total_officers           0
b_female_officers          0
b_male_officers            0
b_female_sho               0
e_total_sampled            0
e_female_sampled           0
e_male_sampled             0
b_total_sampled            0
b_female_sampled           0
b_male_sampled             0
b_total_surveyed           0
b_female_surveyed          0
b_male_surveyed            0
population                 0
urban                      0
dist_urban                 0
strat_pca                  0
treatment                  0
group                      0
dist_id                    0
implement_quality         61
training_score             0
comm_outreach_strength    61
regular_whd                0
women_whd                  0
e_male_weight              0
b_male_weight              0
e_female_weight           16
b_female_weight           12
dtype: int64

In [ ]:
# we expect our 61 nulls in comm_outreach_strength and implementation_quality
# so let's examine the e_female_weight and b_female_weight null instances
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  display(psp_df[psp_df['e_female_weight'].isna() | psp_df['b_female_weight'].isna()])

# CONCLUSION: NaN in these two columns indicate no women were interviewed at b_ or e_

,Unnamed: 0,e_total_surveyed,e_female_surveyed,e_male_surveyed,ps_code,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,e_male_officers,e_female_sho,b_total_staff,b_female_staff,b_male_staff,b_total_officers,b_female_officers,b_male_officers,b_female_sho,e_total_sampled,e_female_sampled,e_male_sampled,b_total_sampled,b_female_sampled,b_male_sampled,b_total_surveyed,b_female_surveyed,b_male_surveyed,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,e_male_weight,b_male_weight,e_female_weight,b_female_weight
1,1,11.0,0.0,11.0,1002.0,29.0,2.0,6.0,0.0,27.0,6.0,0.0,20.0,1.0,19.0,7.0,1.0,6.0,0.0,11.0,0.0,11.0,12.0,1.0,11.0,11.0,0.0,11.0,170000,Rural,1.0,-0.960574,Control,control,1000.0,NaN,1.545454,NaN,0.0,0.0,2.454546,1.727273,NaN,1.0
10,10,12.0,0.0,12.0,2011.0,43.0,3.0,10.0,1.0,40.0,9.0,0.0,24.0,0.0,24.0,7.0,0.0,7.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,12.0,0.0,12.0,58432,Rural,2.0,-1.332458,Treatment,women officers,2000.0,9.0,3.779070,2.16,0.0,1.0,3.333333,2.000000,NaN,NaN
14,14,10.0,0.0,10.0,2015.0,22.0,0.0,2.0,0.0,22.0,2.0,0.0,22.0,2.0,20.0,3.0,0.0,3.0,0.0,10.0,0.0,10.0,12.0,2.0,10.0,11.0,1.0,10.0,94280,Rural,2.0,-1.530201,Treatment,regular mhd,2000.0,9.0,3.875000,2.16,1.0,0.0,2.200000,2.000000,NaN,1.0
28,28,9.0,0.0,9.0,3029.0,32.0,0.0,7.0,0.0,32.0,7.0,0.0,37.0,0.0,37.0,7.0,0.0,7.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,9.0,0.0,9.0,40000,Rural,3.0,-1.836891,Treatment,regular mhd,3000.0,3.0,2.555556,0.01,1.0,0.0,2.666667,3.083333,NaN,NaN
42,42,11.0,0.0,11.0,3043.0,59.0,3.0,7.0,0.0,56.0,7.0,0.0,27.0,0.0,27.0,5.0,0.0,5.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,12.0,0.0,12.0,55557,Rural,3.0,-1.350246,Control,control,3000.0,NaN,0.090909,NaN,0.0,0.0,4.666666,2.250000,NaN,NaN
43,43,10.0,0.0,10.0,3044.0,75.0,6.0,19.0,0.0,69.0,19.0,0.0,62.0,0.0,62.0,17.0,0.0,17.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,12.0,0.0,12.0,45000,Urban,4.0,0.644098,Treatment,women officers,3000.0,7.0,1.400000,2.30,0.0,1.0,5.750000,5.166666,NaN,NaN
48,48,9.0,0.0,9.0,4049.0,17.0,2.0,2.0,1.0,15.0,1.0,0.0,20.0,0.0,20.0,3.0,0.0,3.0,0.0,10.0,0.0,10.0,11.0,0.0,11.0,11.0,0.0,11.0,45000,Rural,5.0,-2.254152,Treatment,women officers,4000.0,8.0,1.000000,2.08,0.0,1.0,1.500000,1.818182,NaN,NaN
50,50,10.0,0.0,10.0,4051.0,27.0,2.0,5.0,0.0,25.0,5.0,0.0,20.0,0.0,20.0,5.0,0.0,5.0,0.0,11.0,0.0,11.0,11.0,0.0,11.0,11.0,0.0,11.0,44854,Rural,5.0,-1.910511,Control,control,4000.0,NaN,0.100000,NaN,0.0,0.0,2.272727,1.818182,NaN,NaN
79,79,11.0,0.0,11.0,5080.0,30.0,0.0,8.0,0.0,30.0,8.0,0.0,28.0,0.0,28.0,6.0,0.0,6.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,12.0,0.0,12.0,115000,Rural,7.0,-1.027928,Treatment,women officers,5000.0,8.0,2.363637,2.04,0.0,1.0,2.500000,2.333333,NaN,NaN
131,131,10.0,0.0,10.0,7132.0,37.0,1.0,9.0,0.0,36.0,9.0,0.0,29.0,1.0,28.0,6.0,1.0,5.0,0.0,10.0,0.0,10.0,11.0,1.0,10.0,11.0,1.0,10.0,105118,Rural,11.0,0.179562,Treatment,women officers,7000.0,9.0,3.622222,3.06,0.0,1.0,3.600000,2.800000,NaN,1.0
155,155,9.0,0.0,9.0,10156.0,21.0,0.0,4.0,0.0,21.0,4.0,0.0,21.0,1.0,20.0,4.0,0.0,4.0,0.0,11.0,0.0,11.0,12.0,1.0,11.0,11.0,1.0,10.0,135817,Rural,15.0,-0.882885,Control,control,10000.0,NaN,0.333333,NaN,0.0,0.0,1.909091,1.818182,NaN,1.0
173,173,10.0,0.0,10.0,12174.0,20.0,1.0,3.0,0.0,19.0,3.0,0.0,15.0,0.0,15.0,3.0,0.0,3.0,0.0,11.0,0.0,11.0,11.0,0.0,11.0,11.0,0.0,11.0,89170,Rural,18.0,-1.428090,Treatment,regular mhd,12000.0,9.0,3.616667,2.12,1.0,0.0,1.727273,1.363636,NaN,NaN
174,174,11.0,0.0,11.0,12175.0,28.0,4.0,5.0,1.0,24.0,4.0,0.0,19.0,0.0,19.0,3.0,0.0,3.0,0.0,11.0,0.0,11.0,11.0,0.0,11.0,11.0,0.0,11.0,74479,Rural,18.0,-1.548632,Treatment,women officers,12000.0,6.0,2.545454,2.02,0.0,1.0,2.181818,1.727273,NaN,NaN
176,176,10.0,0.0,10.0,12177.0,36.0,3.0,5.0,0.0,33.0,5.0,0.0,21.0,0.0,21.0,3.0,0.0,3.0,0.0,11.0,0.0,11.0,11.0,0.0,11.0,11.0,0.0,11.0,151916,Rural,18.0,-0.794338,Treatment,regular mhd,12000.0,7.0,2.911111,2.16,1.0,0.0,3.000000,1.909091,NaN,NaN
177,177,11.0,0.0,11.0,12178.0,23.0,0.0,4.0,0.0,23.0,4.0,0.0,18.0,0.0,18.0,4.0,0.0,4.0,0.0,12.0,0.0,12.0,12.0,0.0,12.0,11.0,0.0,11.0,70000,Rural,18.0,-1.830616,Control,control,12000.0,NaN,0.000000,NaN,0.0,0.0,1.916667,1.500000,NaN,NaN
179,179,11.0,0.0,11.0,12180.0,30.0,5.0,5.0,2.0,25.0,3.0,0.0,21.0,0.0,21.0,5.0,0.0,5.0,0.0,11.0,0.0,11.0,11.0,0.0,11.0,11.0,0.0,11.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,2.272727,1.909091,NaN,NaN

In [ ]:
# I'm not 100% on how this is going to screw up our calculations in the future
# but for now let's sub in 0 for these NaNs
for col in ['b_female_weight','e_female_weight']:
  psp_df[col] = psp_df[col].fillna(0)

# at the same time, give comm_outreach_strength	and implement_quality the same treatment as above
# i.e. fill Null with .mean(), at least for now
for col in ['comm_outreach_strength','implement_quality','training_score']:
  psp_df[col] = psp_df[col].fillna(psp_df[col].mean())

# check with .info()
psp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              180 non-null    int64
 1   e_total_surveyed        180 non-null    float64
 2   e_female_surveyed       180 non-null    float64
 3   e_male_surveyed         180 non-null    float64
 4   ps_code                 180 non-null    float64
 5   e_total_staff           180 non-null    float64
 6   e_female_staff          180 non-null    float64
 7   e_total_officers        180 non-null    float64
 8   e_female_officers       180 non-null    float64
 9   e_male_staff            180 non-null    float64
 10  e_male_officers         180 non-null    float64
 11  e_female_sho            180 non-null    float64
 12  b_total_staff           180 non-null    float64
 13  b_female_staff          180 non-null    float64
 14  b_male_staff            180 non-null    float64
 15  b_total_officers        180 non-null    float64
 16  b_female_officers       180 non-null    float64
 17  b_male_officers         180 non-null    float64
 18  b_female_sho            180 non-null    float64
 19  e_total_sampled         180 non-null    float64
 20  e_female_sampled        180 non-null    float64
 21  e_male_sampled          180 non-null    float64
 22  b_total_sampled         180 non-null    float64
 23  b_female_sampled        180 non-null    float64
 24  b_male_sampled          180 non-null    float64
 25  b_total_surveyed        180 non-null    float64
 26  b_female_surveyed       180 non-null    float64
 27  b_male_surveyed         180 non-null    float64
 28  population              180 non-null    int64
 29  urban                   180 non-null    object
 30  dist_urban              180 non-null    float64
 31  strat_pca               180 non-null    float64
 32  treatment               180 non-null    object
 33  group                   180 non-null    object
 34  dist_id                 180 non-null    float64
 35  implement_quality       180 non-null    float64
 36  training_score          180 non-null    float64
 37  comm_outreach_strength  180 non-null    float64
 38  regular_whd             180 non-null    float64
 39  women_whd               180 non-null    float64
 40  e_male_weight           180 non-null    float64
 41  b_male_weight           180 non-null    float64
 42  e_female_weight         180 non-null    float64
 43  b_female_weight         180 non-null    float64
dtypes: float64(39), int64(2), object(3)
memory usage: 62.0+ KB

In [ ]:
# Once again, let's convert some of these floats to ints

# there are so many we need to convert here, it's easier to list everything
# and then drop what we want to preserve as float or obj
all_cols = list(psp_df)
keep_cols = {'Unnamed: 0','urban','strat_pca','treatment','group','comm_outreach_strength','e_male_weight','b_male_weight','e_female_weight','b_female_weight'}
# credit for the line below to https://stackoverflow.com/questions/36268749/how-to-remove-multiple-items-from-a-list-in-just-one-statement
int_cols = [e for e in all_cols if e not in keep_cols]

# convert our list to int values
for col in int_cols:
  psp_df = psp_df.astype({col:'int'})

# last step let's rename "Unnamed: 0"
psp_df = psp_df.rename(columns={'Unnamed: 0':'station_index'})

# check our work and we're done!
psp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_index           180 non-null    int64
 1   e_total_surveyed        180 non-null    int64
 2   e_female_surveyed       180 non-null    int64
 3   e_male_surveyed         180 non-null    int64
 4   ps_code                 180 non-null    int64
 5   e_total_staff           180 non-null    int64
 6   e_female_staff          180 non-null    int64
 7   e_total_officers        180 non-null    int64
 8   e_female_officers       180 non-null    int64
 9   e_male_staff            180 non-null    int64
 10  e_male_officers         180 non-null    int64
 11  e_female_sho            180 non-null    int64
 12  b_total_staff           180 non-null    int64
 13  b_female_staff          180 non-null    int64
 14  b_male_staff            180 non-null    int64
 15  b_total_officers        180 non-null    int64
 16  b_female_officers       180 non-null    int64
 17  b_male_officers         180 non-null    int64
 18  b_female_sho            180 non-null    int64
 19  e_total_sampled         180 non-null    int64
 20  e_female_sampled        180 non-null    int64
 21  e_male_sampled          180 non-null    int64
 22  b_total_sampled         180 non-null    int64
 23  b_female_sampled        180 non-null    int64
 24  b_male_sampled          180 non-null    int64
 25  b_total_surveyed        180 non-null    int64
 26  b_female_surveyed       180 non-null    int64
 27  b_male_surveyed         180 non-null    int64
 28  population              180 non-null    int64
 29  urban                   180 non-null    object
 30  dist_urban              180 non-null    int64
 31  strat_pca               180 non-null    float64
 32  treatment               180 non-null    object
 33  group                   180 non-null    object
 34  dist_id                 180 non-null    int64
 35  implement_quality       180 non-null    int64
 36  training_score          180 non-null    int64
 37  comm_outreach_strength  180 non-null    float64
 38  regular_whd             180 non-null    int64
 39  women_whd               180 non-null    int64
 40  e_male_weight           180 non-null    float64
 41  b_male_weight           180 non-null    float64
 42  e_female_weight         180 non-null    float64
 43  b_female_weight         180 non-null    float64
dtypes: float64(6), int64(35), object(3)
memory usage: 62.0+ KB

###Step 3.3: Clean `citizen_full_data`

In [ ]:
citizen = data_dic['citizen_full_data']
citizen = citizen.astype({'dist_urban':'int','dist_id':'int','regular_whd':'int','women_whd':'int'})
citizen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6519 entries, 0 to 6518
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              6519 non-null   int64
 1   uid                     6519 non-null   int64
 2   b_visit                 6519 non-null   float64
 3   b_pol_handling          6334 non-null   float64
 4   b_safety                6480 non-null   float64
 5   e_urja_knowledge        3294 non-null   object
 6   e_visit                 3376 non-null   float64
 7   e_pol_handling          3112 non-null   float64
 8   e_safety                3372 non-null   float64
 9   spw                     6519 non-null   float64
 10  e_gender                3376 non-null   object
 11  hh_id                   6519 non-null   float64
 12  member_gender           6519 non-null   object
 13  ps_code                 6519 non-null   float64
 14  population              6519 non-null   int64
 15  urban                   6519 non-null   object
 16  dist_urban              6519 non-null   int64
 17  strat_pca               6519 non-null   float64
 18  treatment               6519 non-null   object
 19  group                   6519 non-null   object
 20  dist_id                 6519 non-null   int64
 21  implement_quality       4291 non-null   float64
 22  training_score          6519 non-null   float64
 23  comm_outreach_strength  4291 non-null   float64
 24  regular_whd             6519 non-null   int64
 25  women_whd               6519 non-null   int64
 26  attrited                6519 non-null   float64
dtypes: float64(14), int64(7), object(6)
memory usage: 1.3+ MB

That is a lot of nulls! (b_pol_handling, b_safety, e_urja_knowledge, e_saftey, e_gender, implement_quality, comm_outreach_strength)

In [ ]:
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
    display(citizen)

,Unnamed: 0,uid,b_visit,b_pol_handling,b_safety,e_urja_knowledge,e_visit,e_pol_handling,e_safety,spw,e_gender,hh_id,member_gender,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,attrited
0,0,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.000000,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
1,1,10512021,0.0,0.000000,3.666667,NaN,NaN,NaN,NaN,0.001526,NaN,1051202.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,1.0
2,2,10512031,0.0,-0.111111,2.333333,No,0.0,0.250000,2.000000,0.001526,Female,1051203.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
3,3,10512041,0.0,-0.200000,3.666667,No,0.0,NaN,3.000000,0.001526,Female,1051204.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
4,4,10512051,0.0,0.000000,3.333333,NaN,NaN,NaN,NaN,0.001526,NaN,1051205.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6514,6514,80602441,0.0,-1.000000,3.000000,NaN,NaN,NaN,NaN,0.003290,NaN,8060244.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,1.0
6515,6515,80602451,0.0,0.000000,3.666667,NaN,NaN,NaN,NaN,0.003290,NaN,8060245.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,1.0
6516,6516,80602461,0.0,0.800000,4.000000,No,0.0,1.000000,3.333333,0.003290,Female,8060246.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6517,6517,80602471,0.0,0.500000,3.333333,No,0.0,1.000000,1.333333,0.003290,Female,8060247.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6518,6518,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.000000,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0

- It is vital to know if people have been to the station before or after baseline, so all nulls must be tossed
- We are fairly interested in how women's health desk affects, so also drop nulls there as well.

In [ ]:
citizen.dropna(subset=['e_visit', 'e_urja_knowledge'], axis=0, inplace=True)
citizen.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3294 entries, 0 to 6518
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3294 non-null   int64
 1   uid                     3294 non-null   int64
 2   b_visit                 3294 non-null   float64
 3   b_pol_handling          3233 non-null   float64
 4   b_safety                3289 non-null   float64
 5   e_urja_knowledge        3294 non-null   object
 6   e_visit                 3294 non-null   float64
 7   e_pol_handling          3061 non-null   float64
 8   e_safety                3294 non-null   float64
 9   spw                     3294 non-null   float64
 10  e_gender                3294 non-null   object
 11  hh_id                   3294 non-null   float64
 12  member_gender           3294 non-null   object
 13  ps_code                 3294 non-null   float64
 14  population              3294 non-null   int64
 15  urban                   3294 non-null   object
 16  dist_urban              3294 non-null   int64
 17  strat_pca               3294 non-null   float64
 18  treatment               3294 non-null   object
 19  group                   3294 non-null   object
 20  dist_id                 3294 non-null   int64
 21  implement_quality       2149 non-null   float64
 22  training_score          3294 non-null   float64
 23  comm_outreach_strength  2149 non-null   float64
 24  regular_whd             3294 non-null   int64
 25  women_whd               3294 non-null   int64
 26  attrited                3294 non-null   float64
dtypes: float64(14), int64(7), object(6)
memory usage: 720.6+ KB

Still some nulls after data cut in half. We will fill in with average to attempt to keep the columns and not throw off existing paterns.

In [ ]:
columnsToFillMean = ['b_pol_handling', 'b_safety', 'e_pol_handling', 'implement_quality', 'comm_outreach_strength']
for col in columnsToFillMean:
  citizen[col] = citizen[col].fillna(citizen[col].mean())

In [ ]:
#Lastly, drop irrelavent columns
citizen.drop(columns='Unnamed: 0', inplace=True)
citizen.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3294 entries, 0 to 6518
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uid                     3294 non-null   int64
 1   b_visit                 3294 non-null   float64
 2   b_pol_handling          3294 non-null   float64
 3   b_safety                3294 non-null   float64
 4   e_urja_knowledge        3294 non-null   object
 5   e_visit                 3294 non-null   float64
 6   e_pol_handling          3294 non-null   float64
 7   e_safety                3294 non-null   float64
 8   spw                     3294 non-null   float64
 9   e_gender                3294 non-null   object
 10  hh_id                   3294 non-null   float64
 11  member_gender           3294 non-null   object
 12  ps_code                 3294 non-null   float64
 13  population              3294 non-null   int64
 14  urban                   3294 non-null   object
 15  dist_urban              3294 non-null   int64
 16  strat_pca               3294 non-null   float64
 17  treatment               3294 non-null   object
 18  group                   3294 non-null   object
 19  dist_id                 3294 non-null   int64
 20  implement_quality       3294 non-null   float64
 21  training_score          3294 non-null   float64
 22  comm_outreach_strength  3294 non-null   float64
 23  regular_whd             3294 non-null   int64
 24  women_whd               3294 non-null   int64
 25  attrited                3294 non-null   float64
dtypes: float64(14), int64(6), object(6)
memory usage: 694.8+ KB

### Step 3.4 Clean `user_survey_endline_data`

In [ ]:
userSurvey_df = data_dic['user_survey_endline_data']
userSurvey_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3251 entries, 0 to 3250
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3251 non-null   int64
 1   uid                     3251 non-null   object
 2   consented               3251 non-null   object
 3   gender                  3251 non-null   object
 4   visitsats               3249 non-null   object
 5   comfort                 3249 non-null   object
 6   respect                 3249 non-null   object
 7   resolution              3204 non-null   object
 8   fclitysats              3228 non-null   object
 9   ps_code                 3251 non-null   float64
 10  population              3251 non-null   int64
 11  urban                   3251 non-null   object
 12  dist_urban              3251 non-null   float64
 13  strat_pca               3251 non-null   float64
 14  treatment               3251 non-null   object
 15  group                   3251 non-null   object
 16  dist_id                 3251 non-null   float64
 17  implement_quality       3251 non-null   float64
 18  training_score          3251 non-null   float64
 19  comm_outreach_strength  3251 non-null   float64
 20  regular_whd             3251 non-null   float64
 21  women_whd               3251 non-null   float64
dtypes: float64(9), int64(2), object(11)
memory usage: 558.9+ KB

Only these are not full: visitsats, comfort, respect, resolution, fclitysats

In [ ]:
userSurvey_df[['visitsats', 'comfort', 'respect', 'resolution', 'fclitysats']]

,visitsats,comfort,respect,resolution,fclitysats
0,Very satisfied,Very comfortable,Very respectfully,Very confident,Very satisfied
1,Somewhat satisfied,Somewhat uncomfortable,Very respectfully,Very confident,Very satisfied
2,Somewhat satisfied,Very comfortable,Somewhat respectfully,Very confident,Somewhat satisfied
3,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Very confident,Somewhat satisfied
4,Very satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied
...,...,...,...,...,...
3246,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied
3247,Very satisfied,Very comfortable,Very respectfully,Very confident,Somewhat satisfied
3248,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied
3249,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied
3250,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied

Since there are not that many nulls, I will ellect to remove them from the dataset. I could chose to fill in the most common occuring, but I think removing these nulls is worth it!

In [ ]:
userSurvey_df.dropna(subset=['visitsats', 'comfort', 'respect', 'resolution', 'fclitysats'], axis=0, inplace=True)
userSurvey_df.drop(columns='Unnamed: 0', inplace=True)
userSurvey_df = userSurvey_df.astype({'dist_urban':'int','dist_id':'int','regular_whd':'int','women_whd':'int'})
userSurvey_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3178 entries, 0 to 3250
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uid                     3178 non-null   object
 1   consented               3178 non-null   object
 2   gender                  3178 non-null   object
 3   visitsats               3178 non-null   object
 4   comfort                 3178 non-null   object
 5   respect                 3178 non-null   object
 6   resolution              3178 non-null   object
 7   fclitysats              3178 non-null   object
 8   ps_code                 3178 non-null   float64
 9   population              3178 non-null   int64
 10  urban                   3178 non-null   object
 11  dist_urban              3178 non-null   int64
 12  strat_pca               3178 non-null   float64
 13  treatment               3178 non-null   object
 14  group                   3178 non-null   object
 15  dist_id                 3178 non-null   int64
 16  implement_quality       3178 non-null   float64
 17  training_score          3178 non-null   float64
 18  comm_outreach_strength  3178 non-null   float64
 19  regular_whd             3178 non-null   int64
 20  women_whd               3178 non-null   int64
dtypes: float64(5), int64(5), object(11)
memory usage: 546.2+ KB

That was easy!

### Step 3.5 Clean `admin_long_data`

In [ ]:
admin_long_df = data_dic['admin_long_data']
admin_long_df = admin_long_df.astype({'dist_urban':'int','dist_id':'int','regular_whd':'int','women_whd':'int'})
admin_long_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              4500 non-null   int64
 1   month                   4500 non-null   object
 2   fir_overall_count       4500 non-null   int64
 3   fir_caw_count           4500 non-null   int64
 4   fir_bywomen_count       4500 non-null   int64
 5   arrest_count            4500 non-null   int64
 6   dir_count               4500 non-null   int64
 7   ncr_count               4500 non-null   int64
 8   dial100_count           4500 non-null   float64
 9   ps_code                 4500 non-null   float64
 10  population              4500 non-null   int64
 11  urban                   4500 non-null   object
 12  dist_urban              4500 non-null   int64
 13  strat_pca               4500 non-null   float64
 14  treatment               4500 non-null   object
 15  group                   4500 non-null   object
 16  dist_id                 4500 non-null   int64
 17  implement_quality       4500 non-null   float64
 18  training_score          4500 non-null   float64
 19  comm_outreach_strength  4500 non-null   float64
 20  regular_whd             4500 non-null   int64
 21  women_whd               4500 non-null   int64
dtypes: float64(6), int64(12), object(4)
memory usage: 773.6+ KB

NO NULLS! WOO!

In [ ]:
admin_long_df.drop(columns='Unnamed: 0', inplace=True)
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
        display(admin_long_df)

,month,fir_overall_count,fir_caw_count,fir_bywomen_count,arrest_count,dir_count,ncr_count,dial100_count,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,2019-06-01,35,8,5,20,0,100,40.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
1,2019-11-01,29,10,4,10,1,0,35.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
2,2018-10-01,26,8,3,12,0,72,25.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
3,2018-11-01,27,8,4,12,0,64,41.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
4,2020-05-01,32,6,4,10,0,22,55.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,2018-07-01,19,2,2,5,0,42,17.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4496,2020-04-01,18,1,1,0,1,31,12.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4497,2018-06-01,43,2,1,0,0,89,29.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4498,2020-02-01,12,1,1,2,1,32,16.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4499,2018-10-01,22,1,1,0,0,36,16.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0

Looks clean as well!

### Step 3.6 Clean `cctv_full_data`

In [ ]:
CCTV_df = data_dic['cctv_full_data']
CCTV_df = CCTV_df.astype({'dist_urban':'int','dist_id':'int','regular_whd':'int','women_whd':'int'})
CCTV_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3416 entries, 0 to 3415
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3416 non-null   int64
 1   ps_code                 3416 non-null   float64
 2   urban                   3416 non-null   object
 3   dist_urban              3416 non-null   int64
 4   strat_pca               3416 non-null   float64
 5   treatment               3416 non-null   object
 6   group                   3416 non-null   object
 7   dist_id                 3416 non-null   int64
 8   implement_quality       2293 non-null   float64
 9   training_score          3416 non-null   float64
 10  comm_outreach_strength  2293 non-null   float64
 11  regular_whd             3416 non-null   int64
 12  women_whd               3416 non-null   int64
 13  dayofweek               3416 non-null   object
 14  timeofday               3416 non-null   object
 15  esum_all_duration       2342 non-null   float64
 16  eavg_all                2347 non-null   float64
 17  eavg_all_pixels         2347 non-null   float64
 18  eavg_all_fps            2347 non-null   float64
 19  esum_women_duration     2338 non-null   float64
 20  eavg_women              2346 non-null   float64
 21  eavg_women_pixels       2346 non-null   float64
 22  eavg_women_fps          2346 non-null   float64
 23  esum_wprop_duration     2288 non-null   float64
 24  eavg_wprop              2341 non-null   float64
 25  eavg_wprop_pixels       2341 non-null   float64
 26  eavg_wprop_fps          2341 non-null   float64
 27  bsum_all_duration       2894 non-null   float64
 28  bavg_all                2900 non-null   float64
 29  bavg_all_pixels         2900 non-null   float64
 30  bavg_all_fps            2900 non-null   float64
 31  bsum_women_duration     2890 non-null   float64
 32  bavg_women              2900 non-null   float64
 33  bavg_women_pixels       2900 non-null   float64
 34  bavg_women_fps          2900 non-null   float64
 35  bsum_wprop_duration     2872 non-null   float64
 36  bavg_wprop              2901 non-null   float64
 37  bavg_wprop_pixels       2901 non-null   float64
 38  bavg_wprop_fps          2901 non-null   float64
dtypes: float64(29), int64(5), object(5)
memory usage: 1.0+ MB

Key Variables are

*   bavg_women (and e)
* bavg_all and (e)
* bavg_wprop and (e)
* dayofweek (no nulls)
* timeofday (no nulls)

So if there are null, we need to fix. Since floats and they cover a lot of data, will fill in average!

In [ ]:
columnsToFillMean = ['bavg_women', 'eavg_women', 'bavg_all','eavg_all', 'bavg_wprop', 'eavg_wprop']
for col in columnsToFillMean:
  CCTV_df[col] = CCTV_df[col].fillna(CCTV_df[col].mean())
CCTV_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3416 entries, 0 to 3415
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3416 non-null   int64
 1   ps_code                 3416 non-null   float64
 2   urban                   3416 non-null   object
 3   dist_urban              3416 non-null   int64
 4   strat_pca               3416 non-null   float64
 5   treatment               3416 non-null   object
 6   group                   3416 non-null   object
 7   dist_id                 3416 non-null   int64
 8   implement_quality       2293 non-null   float64
 9   training_score          3416 non-null   float64
 10  comm_outreach_strength  2293 non-null   float64
 11  regular_whd             3416 non-null   int64
 12  women_whd               3416 non-null   int64
 13  dayofweek               3416 non-null   object
 14  timeofday               3416 non-null   object
 15  esum_all_duration       2342 non-null   float64
 16  eavg_all                3416 non-null   float64
 17  eavg_all_pixels         2347 non-null   float64
 18  eavg_all_fps            2347 non-null   float64
 19  esum_women_duration     2338 non-null   float64
 20  eavg_women              3416 non-null   float64
 21  eavg_women_pixels       2346 non-null   float64
 22  eavg_women_fps          2346 non-null   float64
 23  esum_wprop_duration     2288 non-null   float64
 24  eavg_wprop              3416 non-null   float64
 25  eavg_wprop_pixels       2341 non-null   float64
 26  eavg_wprop_fps          2341 non-null   float64
 27  bsum_all_duration       2894 non-null   float64
 28  bavg_all                3416 non-null   float64
 29  bavg_all_pixels         2900 non-null   float64
 30  bavg_all_fps            2900 non-null   float64
 31  bsum_women_duration     2890 non-null   float64
 32  bavg_women              3416 non-null   float64
 33  bavg_women_pixels       2900 non-null   float64
 34  bavg_women_fps          2900 non-null   float64
 35  bsum_wprop_duration     2872 non-null   float64
 36  bavg_wprop              3416 non-null   float64
 37  bavg_wprop_pixels       2901 non-null   float64
 38  bavg_wprop_fps          2901 non-null   float64
dtypes: float64(29), int64(5), object(5)
memory usage: 1.0+ MB

No we will drop unnecessary columns that contain nulls

In [ ]:
CCTV_df = CCTV_df.dropna(axis=1, how='any')
CCTV_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3416 entries, 0 to 3415
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      3416 non-null   int64
 1   ps_code         3416 non-null   float64
 2   urban           3416 non-null   object
 3   dist_urban      3416 non-null   int64
 4   strat_pca       3416 non-null   float64
 5   treatment       3416 non-null   object
 6   group           3416 non-null   object
 7   dist_id         3416 non-null   int64
 8   training_score  3416 non-null   float64
 9   regular_whd     3416 non-null   int64
 10  women_whd       3416 non-null   int64
 11  dayofweek       3416 non-null   object
 12  timeofday       3416 non-null   object
 13  eavg_all        3416 non-null   float64
 14  eavg_women      3416 non-null   float64
 15  eavg_wprop      3416 non-null   float64
 16  bavg_all        3416 non-null   float64
 17  bavg_women      3416 non-null   float64
 18  bavg_wprop      3416 non-null   float64
dtypes: float64(9), int64(5), object(5)
memory usage: 507.2+ KB

### Step 3.7: Clean `admin_wide_data`

In [ ]:
# extract our data and look at it
admin_wide_df = data_dic['admin_wide_data']
admin_wide_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1980 entries, 0 to 1979
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1980 non-null   int64
 1   ps_code                 1980 non-null   float64
 2   urban                   1980 non-null   object
 3   dist_urban              1980 non-null   float64
 4   strat_pca               1980 non-null   float64
 5   treatment               1980 non-null   object
 6   dist_id                 1980 non-null   float64
 7   regular_whd             1980 non-null   float64
 8   women_whd               1980 non-null   float64
 9   e_caw_rate              1980 non-null   float64
 10  month                   1980 non-null   float64
 11  b_fir_overall_count     1980 non-null   int64
 12  b_fir_caw_count         1980 non-null   int64
 13  b_fir_bywomen_count     1980 non-null   int64
 14  b_arrest_count          1980 non-null   int64
 15  b_dir_count             1980 non-null   int64
 16  b_ncr_count             1980 non-null   int64
 17  b_dial100_count         1980 non-null   float64
 18  e_fir_overall_count     1980 non-null   int64
 19  e_fir_caw_count         1980 non-null   int64
 20  e_fir_bywomen_count     1980 non-null   int64
 21  e_arrest_count          1980 non-null   int64
 22  e_dir_count             1980 non-null   int64
 23  e_ncr_count             1980 non-null   int64
 24  e_dial100_count         1980 non-null   float64
 25  implement_quality       1980 non-null   float64
 26  training_score          1980 non-null   float64
 27  comm_outreach_strength  1980 non-null   float64
dtypes: float64(13), int64(13), object(2)
memory usage: 433.2+ KB

In [ ]:
# incredibly, no null values

# let's drop 'Unnamed: 0'
admin_wide_df.drop(columns='Unnamed: 0',inplace=True)

# let's check our data
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
  display(admin_wide_df)

# Looks pretty good!

,ps_code,urban,dist_urban,strat_pca,treatment,dist_id,regular_whd,women_whd,e_caw_rate,month,b_fir_overall_count,b_fir_caw_count,b_fir_bywomen_count,b_arrest_count,b_dir_count,b_ncr_count,b_dial100_count,e_fir_overall_count,e_fir_caw_count,e_fir_bywomen_count,e_arrest_count,e_dir_count,e_ncr_count,e_dial100_count,implement_quality,training_score,comm_outreach_strength
0,1001.0,Rural,1.0,-0.234041,Treatment,1000.0,0.0,1.0,0.000000,1.0,29,8,5,14,0,51,26.0,30,11,3,13,0,9,30.0,9.0,2.916667,2.20
1,1002.0,Rural,1.0,-0.960574,Control,1000.0,0.0,0.0,0.114887,1.0,17,5,2,10,0,19,15.0,11,2,2,2,0,2,26.0,0.0,1.545454,0.00
2,1003.0,Rural,1.0,1.042663,Control,1000.0,0.0,0.0,0.043200,1.0,50,6,5,4,0,20,12.0,68,14,9,19,0,5,11.0,0.0,1.090909,0.00
3,1004.0,Rural,1.0,-1.590761,Treatment,1000.0,1.0,0.0,0.000000,1.0,20,5,4,5,0,4,9.0,12,2,1,4,2,6,19.0,7.0,3.897297,2.03
4,1005.0,Rural,1.0,-1.570695,Treatment,1000.0,0.0,1.0,0.000000,1.0,11,4,1,2,0,8,12.0,12,0,0,0,0,0,17.0,9.0,4.157658,2.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,12176.0,Rural,18.0,-1.401651,Control,12000.0,0.0,0.0,0.060906,12.0,6,2,2,1,0,20,5.0,9,4,4,1,0,13,16.0,0.0,1.363636,0.00
1976,12177.0,Rural,18.0,-0.794338,Treatment,12000.0,1.0,0.0,0.000000,12.0,7,2,2,2,0,18,11.0,22,8,5,9,8,30,7.0,7.0,2.911111,2.16
1977,12178.0,Rural,18.0,-1.830616,Control,12000.0,0.0,0.0,0.000000,12.0,15,3,3,4,0,29,7.0,14,2,2,0,0,14,13.0,0.0,0.000000,0.00
1978,12179.0,Rural,18.0,0.386970,Treatment,12000.0,0.0,1.0,0.000000,12.0,28,7,4,8,0,54,15.0,24,4,2,1,2,62,12.0,9.0,3.890601,3.21
1979,12180.0,Rural,18.0,-1.210380,Treatment,12000.0,1.0,0.0,0.024804,12.0,16,2,1,0,0,28,10.0,10,0,0,0,2,51,11.0,8.0,3.527859,3.08

### Step 3.8: Clean `police_full_data`

In [ ]:
# grab our data
pol_full_df = data_dic['police_full_data']

# see how it looks
pol_full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1961 entries, 0 to 1960
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1961 non-null   int64
 1   uid                     1961 non-null   int64
 2   gender                  1961 non-null   object
 3   e_wcase                 1948 non-null   object
 4   e_effective             1959 non-null   object
 5   e_false_case            1932 non-null   object
 6   e_helpful               1958 non-null   object
 7   e_add_officer           1955 non-null   object
 8   e_add_female            1956 non-null   object
 9   e_female_better         1956 non-null   object
 10  e_taken_seriously       1951 non-null   object
 11  e_prof_dev              1951 non-null   object
 12  e_work_help             1954 non-null   object
 13  e_pol_impt              1961 non-null   float64
 14  e_thana_impt            1961 non-null   float64
 15  e_sensitivity           1961 non-null   float64
 16  ps_code                 1961 non-null   float64
 17  population              1961 non-null   int64
 18  urban                   1961 non-null   object
 19  dist_urban              1961 non-null   float64
 20  strat_pca               1961 non-null   float64
 21  treatment               1961 non-null   object
 22  group                   1961 non-null   object
 23  dist_id                 1961 non-null   float64
 24  implement_quality       1295 non-null   float64
 25  training_score          1961 non-null   float64
 26  comm_outreach_strength  1295 non-null   float64
 27  regular_whd             1961 non-null   float64
 28  women_whd               1961 non-null   float64
 29  b_wcase                 1961 non-null   float64
 30  b_effective             1961 non-null   float64
 31  b_pol_impt              1961 non-null   float64
 32  b_thana_impt            1961 non-null   float64
 33  b_sensitivity           1961 non-null   float64
 34  b_helpful               1961 non-null   float64
 35  b_female_better         1961 non-null   float64
 36  b_add_officer           1961 non-null   float64
 37  b_add_female            1961 non-null   float64
dtypes: float64(21), int64(3), object(14)
memory usage: 582.3+ KB

In [ ]:
# let's count our null values by column
pol_full_df.isna().sum()

Unnamed: 0                  0
uid                         0
gender                      0
e_wcase                    13
e_effective                 2
e_false_case               29
e_helpful                   3
e_add_officer               6
e_add_female                5
e_female_better             5
e_taken_seriously          10
e_prof_dev                 10
e_work_help                 7
e_pol_impt                  0
e_thana_impt                0
e_sensitivity               0
ps_code                     0
population                  0
urban                       0
dist_urban                  0
strat_pca                   0
treatment                   0
group                       0
dist_id                     0
implement_quality         666
training_score              0
comm_outreach_strength    666
regular_whd                 0
women_whd                   0
b_wcase                     0
b_effective                 0
b_pol_impt                  0
b_thana_impt                0
b_sensitivity               0
b_helpful                   0
b_female_better             0
b_add_officer               0
b_add_female                0
dtype: int64

In [ ]:
# we're missing only a few answers from our e_ question set
# so let's drop those rows
drop_e = ['e_wcase','e_effective','e_false_case','e_helpful','e_add_officer','e_add_female','e_female_better','e_taken_seriously','e_prof_dev','e_work_help']
pol_full_df.dropna(subset=drop_e, axis=0, inplace=True)

# check our work
pol_full_df.shape
# pol_full_df.isna().sum()

(1904, 38)

In [ ]:
# we'll treat our implement_quality and comm_outreach_strength as before
# by subbing in the mean
for col in ['implement_quality','comm_outreach_strength']:
  pol_full_df[col] = pol_full_df[col].fillna(pol_full_df[col].mean())

# also let's drop that Unnamed column again
pol_full_df.drop(columns='Unnamed: 0', inplace=True)

# take a look and we should be set
pol_full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1904 entries, 0 to 1960
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uid                     1904 non-null   int64
 1   gender                  1904 non-null   object
 2   e_wcase                 1904 non-null   object
 3   e_effective             1904 non-null   object
 4   e_false_case            1904 non-null   object
 5   e_helpful               1904 non-null   object
 6   e_add_officer           1904 non-null   object
 7   e_add_female            1904 non-null   object
 8   e_female_better         1904 non-null   object
 9   e_taken_seriously       1904 non-null   object
 10  e_prof_dev              1904 non-null   object
 11  e_work_help             1904 non-null   object
 12  e_pol_impt              1904 non-null   float64
 13  e_thana_impt            1904 non-null   float64
 14  e_sensitivity           1904 non-null   float64
 15  ps_code                 1904 non-null   float64
 16  population              1904 non-null   int64
 17  urban                   1904 non-null   object
 18  dist_urban              1904 non-null   float64
 19  strat_pca               1904 non-null   float64
 20  treatment               1904 non-null   object
 21  group                   1904 non-null   object
 22  dist_id                 1904 non-null   float64
 23  implement_quality       1904 non-null   float64
 24  training_score          1904 non-null   float64
 25  comm_outreach_strength  1904 non-null   float64
 26  regular_whd             1904 non-null   float64
 27  women_whd               1904 non-null   float64
 28  b_wcase                 1904 non-null   float64
 29  b_effective             1904 non-null   float64
 30  b_pol_impt              1904 non-null   float64
 31  b_thana_impt            1904 non-null   float64
 32  b_sensitivity           1904 non-null   float64
 33  b_helpful               1904 non-null   float64
 34  b_female_better         1904 non-null   float64
 35  b_add_officer           1904 non-null   float64
 36  b_add_female            1904 non-null   float64
dtypes: float64(21), int64(2), object(14)
memory usage: 565.2+ KB

## **Step 4: Organize**
Lets get organized, organized

In [ ]:
dataQOne = {'Stations':psp_df, 'Police':pol_full_df, 'Random':random_df}
dataQTwo = {'Admin_Wide':admin_wide_df, 'Citizen':citizen, 'Random':random_df}
dataQThree = {'Citizen':citizen, 'Random_Heterogeninty':random_df, 'User_Survery':userSurvey_df}
dataQFour = {'Random':random_df, 'Admin':admin_long_df, 'Police_Survery':psp_df, 'CCTV':CCTV_df}

In [ ]:
relaventData = [('Question 1', dataQOne),('Question 2', dataQTwo),('Question 3', dataQThree), ('Question 4', dataQFour)]

In [ ]:
for i in relaventData:
  print(i[0])
  for key, value in i[1].items():
      print(key)
      with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
        display(value)

Question 1
Stations

,station_index,e_total_surveyed,e_female_surveyed,e_male_surveyed,ps_code,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,e_male_officers,e_female_sho,b_total_staff,b_female_staff,b_male_staff,b_total_officers,b_female_officers,b_male_officers,b_female_sho,e_total_sampled,e_female_sampled,e_male_sampled,b_total_sampled,b_female_sampled,b_male_sampled,b_total_surveyed,b_female_surveyed,b_male_surveyed,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,e_male_weight,b_male_weight,e_female_weight,b_female_weight
0,0,12,1,11,1001,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,129345,Rural,1,-0.234041,Treatment,women officers,1000,9,2,2.200000,0,1,3.818182,3.272727,6.000000,3.000000
1,1,11,0,11,1002,29,2,6,0,27,6,0,20,1,19,7,1,6,0,11,0,11,12,1,11,11,0,11,170000,Rural,1,-0.960574,Control,control,1000,7,1,1.798067,0,0,2.454546,1.727273,0.000000,1.000000
2,2,11,1,10,1003,79,6,13,2,73,11,0,56,7,49,12,2,10,0,12,2,10,12,2,10,11,2,9,102467,Rural,1,1.042663,Control,control,1000,7,1,1.798067,0,0,7.300000,4.900000,3.000000,3.500000
3,3,10,2,8,1004,33,3,7,1,30,6,0,22,4,18,4,1,3,0,13,3,10,13,3,10,13,3,10,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7,3,2.030000,1,0,3.000000,1.800000,1.000000,1.333333
4,4,12,3,9,1005,32,7,4,2,25,2,1,28,3,25,6,0,6,0,12,3,9,12,2,10,12,2,10,76376,Rural,1,-1.570695,Treatment,women officers,1000,9,4,2.200000,0,1,2.777778,2.500000,2.333333,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,11,1,10,12176,35,7,6,2,28,4,0,30,2,28,4,0,4,0,12,1,11,12,1,11,11,1,10,23565,Rural,18,-1.401651,Control,control,12000,7,1,1.798067,0,0,2.545454,2.545454,7.000000,2.000000
176,176,10,0,10,12177,36,3,5,0,33,5,0,21,0,21,3,0,3,0,11,0,11,11,0,11,11,0,11,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7,2,2.160000,1,0,3.000000,1.909091,0.000000,0.000000
177,177,11,0,11,12178,23,0,4,0,23,4,0,18,0,18,4,0,4,0,12,0,12,12,0,12,11,0,11,70000,Rural,18,-1.830616,Control,control,12000,7,0,1.798067,0,0,1.916667,1.500000,0.000000,0.000000
178,178,11,2,9,12179,53,9,7,3,44,4,1,40,1,39,6,0,6,0,11,2,9,11,1,10,10,0,10,165000,Rural,18,0.386970,Treatment,women officers,12000,9,3,3.210000,0,1,4.888889,3.900000,4.500000,1.000000
179,179,11,0,11,12180,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8,3,3.080000,1,0,2.272727,1.909091,0.000000,0.000000

Police

,uid,gender,e_wcase,e_effective,e_false_case,e_helpful,e_add_officer,e_add_female,e_female_better,e_taken_seriously,e_prof_dev,e_work_help,e_pol_impt,e_thana_impt,e_sensitivity,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,b_wcase,b_effective,b_pol_impt,b_thana_impt,b_sensitivity,b_helpful,b_female_better,b_add_officer,b_add_female
0,2240137,male,too much attention,very effective,common,very helpful,more effective,Less effective,female,disagree,disagree,disagree,1.0,0.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6
1,2240133,male,too much attention,very effective,common,very helpful,much more effective,No difference,female,strongly agree,strongly agree,disagree,1.0,1.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6
2,2240136,male,too much attention,very effective,uncommon,very helpful,much more effective,Less effective,female,disagree,disagree,strongly disagree,0.0,0.0,12.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6
3,2240132,female,too much attention,very effective,common,helpful,much more effective,Less effective,female,agree,agree,disagree,1.0,1.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6
4,2240134,male,too much attention,very effective,very common,very helpful,much more effective,No difference,female,agree,disagree,disagree,1.0,1.0,7.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1956,3257338,male,enough attention,very effective,uncommon,very helpful,more effective,No difference,female,agree,agree,disagree,0.0,0.0,6.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,4.0,0.0,0.0,6.0,5.0,3.0,5.0,5.0
1957,3257336,male,too much attention,effective,uncommon,helpful,more effective,No difference,female,agree,agree,agree,0.0,1.0,8.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,5.0,0.0,1.0,12.0,5.0,3.0,5.0,5.0
1958,3257339,male,enough attention,effective,very common,very helpful,much more effective,Less effective,female,strongly agree,agree,disagree,0.0,0.0,4.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,5.0,0.0,1.0,4.0,5.0,3.0,5.0,4.0
1959,3257341,male,too much attention,effective,common,helpful,more effective,No difference,female,agree,agree,agree,1.0,0.0,7.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,4.0,0.0,0.0,5.0,5.0,3.0,5.0,4.0
1960,3257340,male,enough attention,very effective,uncommon,helpful,much more effective,Less effective,female,agree,agree,agree,0.0,0.0,8.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,2.0,5.0,0.0,0.0,7.0,4.0,3.0,4.0,4.0

Random

,rand_index,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,0,47,412,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.000000,2.916667,2.200000,0,1
1,1,29,218,170000,Rural,1,-0.960574,Control,control,1000,7.462185,1.545454,1.798067,0,0
2,2,75,694,102467,Rural,1,1.042663,Control,control,1000,7.462185,1.090909,1.798067,0,0
3,3,40,144,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7.000000,3.897297,2.030000,1,0
4,4,37,130,76376,Rural,1,-1.570695,Treatment,women officers,1000,9.000000,4.157658,2.200000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,51,186,23565,Rural,18,-1.401651,Control,control,12000,7.462185,1.363636,1.798067,0,0
176,176,41,221,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7.000000,2.911111,2.160000,1,0
177,177,30,105,70000,Rural,18,-1.830616,Control,control,12000,7.462185,0.000000,1.798067,0,0
178,178,65,423,165000,Rural,18,0.386970,Treatment,women officers,12000,9.000000,3.890601,3.210000,0,1
179,179,30,304,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.000000,3.527859,3.080000,1,0

Question 2
Admin_Wide

,ps_code,urban,dist_urban,strat_pca,treatment,dist_id,regular_whd,women_whd,e_caw_rate,month,b_fir_overall_count,b_fir_caw_count,b_fir_bywomen_count,b_arrest_count,b_dir_count,b_ncr_count,b_dial100_count,e_fir_overall_count,e_fir_caw_count,e_fir_bywomen_count,e_arrest_count,e_dir_count,e_ncr_count,e_dial100_count,implement_quality,training_score,comm_outreach_strength
0,1001.0,Rural,1.0,-0.234041,Treatment,1000.0,0.0,1.0,0.000000,1.0,29,8,5,14,0,51,26.0,30,11,3,13,0,9,30.0,9.0,2.916667,2.20
1,1002.0,Rural,1.0,-0.960574,Control,1000.0,0.0,0.0,0.114887,1.0,17,5,2,10,0,19,15.0,11,2,2,2,0,2,26.0,0.0,1.545454,0.00
2,1003.0,Rural,1.0,1.042663,Control,1000.0,0.0,0.0,0.043200,1.0,50,6,5,4,0,20,12.0,68,14,9,19,0,5,11.0,0.0,1.090909,0.00
3,1004.0,Rural,1.0,-1.590761,Treatment,1000.0,1.0,0.0,0.000000,1.0,20,5,4,5,0,4,9.0,12,2,1,4,2,6,19.0,7.0,3.897297,2.03
4,1005.0,Rural,1.0,-1.570695,Treatment,1000.0,0.0,1.0,0.000000,1.0,11,4,1,2,0,8,12.0,12,0,0,0,0,0,17.0,9.0,4.157658,2.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,12176.0,Rural,18.0,-1.401651,Control,12000.0,0.0,0.0,0.060906,12.0,6,2,2,1,0,20,5.0,9,4,4,1,0,13,16.0,0.0,1.363636,0.00
1976,12177.0,Rural,18.0,-0.794338,Treatment,12000.0,1.0,0.0,0.000000,12.0,7,2,2,2,0,18,11.0,22,8,5,9,8,30,7.0,7.0,2.911111,2.16
1977,12178.0,Rural,18.0,-1.830616,Control,12000.0,0.0,0.0,0.000000,12.0,15,3,3,4,0,29,7.0,14,2,2,0,0,14,13.0,0.0,0.000000,0.00
1978,12179.0,Rural,18.0,0.386970,Treatment,12000.0,0.0,1.0,0.000000,12.0,28,7,4,8,0,54,15.0,24,4,2,1,2,62,12.0,9.0,3.890601,3.21
1979,12180.0,Rural,18.0,-1.210380,Treatment,12000.0,1.0,0.0,0.024804,12.0,16,2,1,0,0,28,10.0,10,0,0,0,2,51,11.0,8.0,3.527859,3.08

Citizen

,uid,b_visit,b_pol_handling,b_safety,e_urja_knowledge,e_visit,e_pol_handling,e_safety,spw,e_gender,hh_id,member_gender,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,attrited
0,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.000000,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
2,10512031,0.0,-0.111111,2.333333,No,0.0,0.250000,2.000000,0.001526,Female,1051203.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
3,10512041,0.0,-0.200000,3.666667,No,0.0,0.535941,3.000000,0.001526,Female,1051204.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
10,10512141,0.0,0.000000,3.666667,No,0.0,1.000000,3.000000,0.001526,Female,1051214.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
13,10512171,1.0,0.000000,3.333333,No,0.0,0.333333,2.000000,0.001526,Female,1051217.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6512,80602421,0.0,0.000000,3.000000,No,0.0,0.000000,4.000000,0.003290,Female,8060242.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6513,80602431,0.0,0.000000,3.000000,No,0.0,1.000000,3.333333,0.003290,Female,8060243.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6516,80602461,0.0,0.800000,4.000000,No,0.0,1.000000,3.333333,0.003290,Female,8060246.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6517,80602471,0.0,0.500000,3.333333,No,0.0,1.000000,1.333333,0.003290,Female,8060247.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6518,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.000000,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0

Random

,rand_index,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,0,47,412,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.000000,2.916667,2.200000,0,1
1,1,29,218,170000,Rural,1,-0.960574,Control,control,1000,7.462185,1.545454,1.798067,0,0
2,2,75,694,102467,Rural,1,1.042663,Control,control,1000,7.462185,1.090909,1.798067,0,0
3,3,40,144,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7.000000,3.897297,2.030000,1,0
4,4,37,130,76376,Rural,1,-1.570695,Treatment,women officers,1000,9.000000,4.157658,2.200000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,51,186,23565,Rural,18,-1.401651,Control,control,12000,7.462185,1.363636,1.798067,0,0
176,176,41,221,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7.000000,2.911111,2.160000,1,0
177,177,30,105,70000,Rural,18,-1.830616,Control,control,12000,7.462185,0.000000,1.798067,0,0
178,178,65,423,165000,Rural,18,0.386970,Treatment,women officers,12000,9.000000,3.890601,3.210000,0,1
179,179,30,304,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.000000,3.527859,3.080000,1,0

Question 3
Citizen

,uid,b_visit,b_pol_handling,b_safety,e_urja_knowledge,e_visit,e_pol_handling,e_safety,spw,e_gender,hh_id,member_gender,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,attrited
0,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.000000,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
2,10512031,0.0,-0.111111,2.333333,No,0.0,0.250000,2.000000,0.001526,Female,1051203.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
3,10512041,0.0,-0.200000,3.666667,No,0.0,0.535941,3.000000,0.001526,Female,1051204.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
10,10512141,0.0,0.000000,3.666667,No,0.0,1.000000,3.000000,0.001526,Female,1051214.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
13,10512171,1.0,0.000000,3.333333,No,0.0,0.333333,2.000000,0.001526,Female,1051217.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6512,80602421,0.0,0.000000,3.000000,No,0.0,0.000000,4.000000,0.003290,Female,8060242.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6513,80602431,0.0,0.000000,3.000000,No,0.0,1.000000,3.333333,0.003290,Female,8060243.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6516,80602461,0.0,0.800000,4.000000,No,0.0,1.000000,3.333333,0.003290,Female,8060246.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6517,80602471,0.0,0.500000,3.333333,No,0.0,1.000000,1.333333,0.003290,Female,8060247.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0
6518,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.000000,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0

Random_Heterogeninty

,rand_index,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,0,47,412,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.000000,2.916667,2.200000,0,1
1,1,29,218,170000,Rural,1,-0.960574,Control,control,1000,7.462185,1.545454,1.798067,0,0
2,2,75,694,102467,Rural,1,1.042663,Control,control,1000,7.462185,1.090909,1.798067,0,0
3,3,40,144,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7.000000,3.897297,2.030000,1,0
4,4,37,130,76376,Rural,1,-1.570695,Treatment,women officers,1000,9.000000,4.157658,2.200000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,51,186,23565,Rural,18,-1.401651,Control,control,12000,7.462185,1.363636,1.798067,0,0
176,176,41,221,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7.000000,2.911111,2.160000,1,0
177,177,30,105,70000,Rural,18,-1.830616,Control,control,12000,7.462185,0.000000,1.798067,0,0
178,178,65,423,165000,Rural,18,0.386970,Treatment,women officers,12000,9.000000,3.890601,3.210000,0,1
179,179,30,304,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.000000,3.527859,3.080000,1,0

User_Survery

,uid,consented,gender,visitsats,comfort,respect,resolution,fclitysats,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,2153QSR,yes,female,Very satisfied,Very comfortable,Very respectfully,Very confident,Very satisfied,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
1,20519SG,yes,female,Somewhat satisfied,Somewhat uncomfortable,Very respectfully,Very confident,Very satisfied,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
2,2051HG7,yes,male,Somewhat satisfied,Very comfortable,Somewhat respectfully,Very confident,Somewhat satisfied,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
3,2051QJF,yes,female,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Very confident,Somewhat satisfied,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
4,2051KRN,yes,male,Very satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,8060N46,yes,female,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
3247,8060QOI,yes,male,Very satisfied,Very comfortable,Very respectfully,Very confident,Somewhat satisfied,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
3248,8060M0Z,yes,male,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
3249,8060C1R,yes,female,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
3250,8060RAF,yes,female,Somewhat satisfied,Somewhat comfortable,Somewhat respectfully,Somewhat confident,Somewhat satisfied,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0

Question 4
Random

,rand_index,total_assigned_officers,total_fir_2017,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,0,47,412,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.000000,2.916667,2.200000,0,1
1,1,29,218,170000,Rural,1,-0.960574,Control,control,1000,7.462185,1.545454,1.798067,0,0
2,2,75,694,102467,Rural,1,1.042663,Control,control,1000,7.462185,1.090909,1.798067,0,0
3,3,40,144,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7.000000,3.897297,2.030000,1,0
4,4,37,130,76376,Rural,1,-1.570695,Treatment,women officers,1000,9.000000,4.157658,2.200000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,51,186,23565,Rural,18,-1.401651,Control,control,12000,7.462185,1.363636,1.798067,0,0
176,176,41,221,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7.000000,2.911111,2.160000,1,0
177,177,30,105,70000,Rural,18,-1.830616,Control,control,12000,7.462185,0.000000,1.798067,0,0
178,178,65,423,165000,Rural,18,0.386970,Treatment,women officers,12000,9.000000,3.890601,3.210000,0,1
179,179,30,304,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.000000,3.527859,3.080000,1,0

Admin

,month,fir_overall_count,fir_caw_count,fir_bywomen_count,arrest_count,dir_count,ncr_count,dial100_count,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd
0,2019-06-01,35,8,5,20,0,100,40.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
1,2019-11-01,29,10,4,10,1,0,35.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
2,2018-10-01,26,8,3,12,0,72,25.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
3,2018-11-01,27,8,4,12,0,64,41.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
4,2020-05-01,32,6,4,10,0,22,55.0,1001.0,129345,Rural,1,-0.234041,Treatment,women officers,1000,9.0,2.916667,2.20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,2018-07-01,19,2,2,5,0,42,17.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4496,2020-04-01,18,1,1,0,1,31,12.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4497,2018-06-01,43,2,1,0,0,89,29.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4498,2020-02-01,12,1,1,2,1,32,16.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0
4499,2018-10-01,22,1,1,0,0,36,16.0,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0

Police_Survery

,station_index,e_total_surveyed,e_female_surveyed,e_male_surveyed,ps_code,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,e_male_officers,e_female_sho,b_total_staff,b_female_staff,b_male_staff,b_total_officers,b_female_officers,b_male_officers,b_female_sho,e_total_sampled,e_female_sampled,e_male_sampled,b_total_sampled,b_female_sampled,b_male_sampled,b_total_surveyed,b_female_surveyed,b_male_surveyed,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,e_male_weight,b_male_weight,e_female_weight,b_female_weight
0,0,12,1,11,1001,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,129345,Rural,1,-0.234041,Treatment,women officers,1000,9,2,2.200000,0,1,3.818182,3.272727,6.000000,3.000000
1,1,11,0,11,1002,29,2,6,0,27,6,0,20,1,19,7,1,6,0,11,0,11,12,1,11,11,0,11,170000,Rural,1,-0.960574,Control,control,1000,7,1,1.798067,0,0,2.454546,1.727273,0.000000,1.000000
2,2,11,1,10,1003,79,6,13,2,73,11,0,56,7,49,12,2,10,0,12,2,10,12,2,10,11,2,9,102467,Rural,1,1.042663,Control,control,1000,7,1,1.798067,0,0,7.300000,4.900000,3.000000,3.500000
3,3,10,2,8,1004,33,3,7,1,30,6,0,22,4,18,4,1,3,0,13,3,10,13,3,10,13,3,10,54000,Rural,1,-1.590761,Treatment,regular mhd,1000,7,3,2.030000,1,0,3.000000,1.800000,1.000000,1.333333
4,4,12,3,9,1005,32,7,4,2,25,2,1,28,3,25,6,0,6,0,12,3,9,12,2,10,12,2,10,76376,Rural,1,-1.570695,Treatment,women officers,1000,9,4,2.200000,0,1,2.777778,2.500000,2.333333,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,11,1,10,12176,35,7,6,2,28,4,0,30,2,28,4,0,4,0,12,1,11,12,1,11,11,1,10,23565,Rural,18,-1.401651,Control,control,12000,7,1,1.798067,0,0,2.545454,2.545454,7.000000,2.000000
176,176,10,0,10,12177,36,3,5,0,33,5,0,21,0,21,3,0,3,0,11,0,11,11,0,11,11,0,11,151916,Rural,18,-0.794338,Treatment,regular mhd,12000,7,2,2.160000,1,0,3.000000,1.909091,0.000000,0.000000
177,177,11,0,11,12178,23,0,4,0,23,4,0,18,0,18,4,0,4,0,12,0,12,12,0,12,11,0,11,70000,Rural,18,-1.830616,Control,control,12000,7,0,1.798067,0,0,1.916667,1.500000,0.000000,0.000000
178,178,11,2,9,12179,53,9,7,3,44,4,1,40,1,39,6,0,6,0,11,2,9,11,1,10,10,0,10,165000,Rural,18,0.386970,Treatment,women officers,12000,9,3,3.210000,0,1,4.888889,3.900000,4.500000,1.000000
179,179,11,0,11,12180,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8,3,3.080000,1,0,2.272727,1.909091,0.000000,0.000000

CCTV

,Unnamed: 0,ps_code,urban,dist_urban,strat_pca,treatment,group,dist_id,training_score,regular_whd,women_whd,dayofweek,timeofday,eavg_all,eavg_women,eavg_wprop,bavg_all,bavg_women,bavg_wprop
0,0,1001.0,Rural,1,-0.234041,Treatment,women officers,1000,2.916667,0,1,Thu,morning,255.564060,11.876471,0.045578,69.000000,3.000000,0.040147
1,1,1002.0,Rural,1,-0.960574,Control,control,1000,1.545454,0,0,Mon,evening,76.029686,16.920221,0.206208,67.200000,10.800000,0.193587
2,2,1003.0,Rural,1,1.042663,Control,control,1000,1.090909,0,0,Sun,morning,134.501400,2.782788,0.020138,145.156894,13.295626,0.089801
3,3,1004.0,Rural,1,-1.590761,Treatment,regular mhd,1000,3.897297,1,0,Sat,evening,114.906030,1.166559,0.009661,145.156894,13.295626,0.089801
4,4,1005.0,Rural,1,-1.570695,Treatment,women officers,1000,4.157658,0,1,Thu,morning,145.051802,14.689332,0.099037,139.306850,13.524937,0.118475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411,3411,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Wed,evening,85.364350,16.106482,0.201576,145.156894,13.295626,0.089801
3412,3412,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Mon,evening,145.051802,14.689332,0.099037,55.612656,9.521234,0.173972
3413,3413,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Mon,morning,145.051802,14.689332,0.099037,87.081830,6.381884,0.055709
3414,3414,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Fri,morning,97.801315,1.657649,0.018386,65.137810,4.165790,0.070516
3415,3415,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Tue,morning,140.565430,5.967400,0.040269,68.704315,10.950302,0.154253

* Question 1
  * We want to join the police officer survey information (pol_full_df) with their respective station information (psp_df). It appears both have already incorporated the Randomization data (random_df).
* Question 2
  * The information we need appears to be contained in admin_wide_data. To answer a subquestion about citizen trust, we could try joining admin_wide_data with citizen_full_data.
* Question 3
  * Since Citizen posseses WHD information already, no joins seem realvent. Also, no joins make sense based on understanding individuals since uids do not map from citizen to user_survery, so no joins there.
* Question 4
  * We want to join CCTV with police survery on station ID. We want to know the number of women at the stations so we can see how they affect the amount of people entering. That will be only join for now. It may eventually be adventageous to join with admin data as well, but it may not be neccessary and could involve some amount aggreation to get it in a good format to join. We plan to cross that bridge when we arrive, but for now we can relate findings from the datasets based on station codes.

### Step 4.1: Merge Police Survey with Police Station Personnel (Q1)

In [ ]:
# first let's check if/how many columns are duplicated

# store columns as lists
pol_full = list(pol_full_df)
psp = list(psp_df)

# print to debug
# print(pol_full)
# print(psp)

# find duplicate columns
intersection = []
for col in pol_full:
  if col in psp:
    intersection.append(col)
print(intersection)

['ps_code', 'population', 'urban', 'dist_urban', 'strat_pca', 'treatment', 'group', 'dist_id', 'implement_quality', 'training_score', 'comm_outreach_strength', 'regular_whd', 'women_whd']

In [ ]:
# let's drop the duplicate columns from psp for now
# but we'll keep ps_code as our matching key
intersection.remove('ps_code')
psp_short_df = psp_df.drop(columns = intersection)

# now let's do a left merge pol_full > psp_short
pol_and_station = pd.merge(pol_full_df,psp_short_df,how='left',on='ps_code')

In [ ]:
# check the output
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
  display(pol_and_station)

,uid,gender,e_wcase,e_effective,e_false_case,e_helpful,e_add_officer,e_add_female,e_female_better,e_taken_seriously,e_prof_dev,e_work_help,e_pol_impt,e_thana_impt,e_sensitivity,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,b_wcase,b_effective,b_pol_impt,b_thana_impt,b_sensitivity,b_helpful,b_female_better,b_add_officer,b_add_female,station_index,e_total_surveyed,e_female_surveyed,e_male_surveyed,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,e_male_officers,e_female_sho,b_total_staff,b_female_staff,b_male_staff,b_total_officers,b_female_officers,b_male_officers,b_female_sho,e_total_sampled,e_female_sampled,e_male_sampled,b_total_sampled,b_female_sampled,b_male_sampled,b_total_surveyed,b_female_surveyed,b_male_surveyed,e_male_weight,b_male_weight,e_female_weight,b_female_weight
0,2240137,male,too much attention,very effective,common,very helpful,more effective,Less effective,female,disagree,disagree,disagree,1.0,0.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,3.818182,3.272727,6.0,3.0
1,2240133,male,too much attention,very effective,common,very helpful,much more effective,No difference,female,strongly agree,strongly agree,disagree,1.0,1.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,3.818182,3.272727,6.0,3.0
2,2240136,male,too much attention,very effective,uncommon,very helpful,much more effective,Less effective,female,disagree,disagree,strongly disagree,0.0,0.0,12.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,3.818182,3.272727,6.0,3.0
3,2240132,female,too much attention,very effective,common,helpful,much more effective,Less effective,female,agree,agree,disagree,1.0,1.0,9.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,3.818182,3.272727,6.0,3.0
4,2240134,male,too much attention,very effective,very common,very helpful,much more effective,No difference,female,agree,disagree,disagree,1.0,1.0,7.0,1001.0,129345,Rural,1.0,-0.234041,Treatment,women officers,1000.0,9.0,2.916667,2.20,0.0,1.0,2.7,4.5,0.5,0.4,7.3,4.2,2.7,4.5,4.6,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,3.818182,3.272727,6.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,3257338,male,enough attention,very effective,uncommon,very helpful,more effective,No difference,female,agree,agree,disagree,0.0,0.0,6.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,4.0,0.0,0.0,6.0,5.0,3.0,5.0,5.0,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,2.272727,1.909091,0.0,0.0
1900,3257336,male,too much attention,effective,uncommon,helpful,more effective,No difference,female,agree,agree,agree,0.0,1.0,8.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,5.0,0.0,1.0,12.0,5.0,3.0,5.0,5.0,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,2.272727,1.909091,0.0,0.0
1901,3257339,male,enough attention,effective,very common,very helpful,much more effective,Less effective,female,strongly agree,agree,disagree,0.0,0.0,4.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,5.0,0.0,1.0,4.0,5.0,3.0,5.0,4.0,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,2.272727,1.909091,0.0,0.0
1902,3257341,male,too much attention,effective,common,helpful,more effective,No difference,female,agree,agree,agree,1.0,0.0,7.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,3.0,4.0,0.0,0.0,5.0,5.0,3.0,5.0,4.0,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,2.272727,1.909091,0.0,0.0
1903,3257340,male,enough attention,very effective,uncommon,helpful,much more effective,Less effective,female,agree,agree,agree,0.0,0.0,8.0,12180.0,77000,Rural,18.0,-1.210380,Treatment,regular mhd,12000.0,8.0,3.527859,3.08,1.0,0.0,2.0,5.0,0.0,0.0,7.0,4.0,3.0,4.0,4.0,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,2.272727,1.909091,0.0,0.0

### Step 4.2: Merge Admin data with Citizen Survey data (Q2)

In [ ]:
# again, let's check if/how many columns are duplicated

# store columns as lists
admin_wide_col = list(admin_wide_df)
citizen_col = list(citizen)

# print to debug
# print(admin_wide_col)
# print(citizen_col)

# find duplicate columns
intersection = []
for col in admin_wide_col:
  if col in citizen_col:
    intersection.append(col)
print(intersection)

['ps_code', 'urban', 'dist_urban', 'strat_pca', 'treatment', 'dist_id', 'regular_whd', 'women_whd', 'implement_quality', 'training_score', 'comm_outreach_strength']

In [ ]:
# let's drop the duplicate columns from admin_wide for now
# but we'll keep ps_code as our matching key
intersection.remove('ps_code')
admin_short_df = admin_wide_df.drop(columns = intersection)

# now let's do a left merge citizen > admin
citizen_and_admin = pd.merge(citizen,admin_short_df,how='left',on='ps_code')

In [ ]:
# check the output
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
  display(citizen_and_admin)

,uid,b_visit,b_pol_handling,b_safety,e_urja_knowledge,e_visit,e_pol_handling,e_safety,spw,e_gender,hh_id,member_gender,ps_code,population,urban,dist_urban,strat_pca,treatment,group,dist_id,implement_quality,training_score,comm_outreach_strength,regular_whd,women_whd,attrited,e_caw_rate,month,b_fir_overall_count,b_fir_caw_count,b_fir_bywomen_count,b_arrest_count,b_dir_count,b_ncr_count,b_dial100_count,e_fir_overall_count,e_fir_caw_count,e_fir_bywomen_count,e_arrest_count,e_dir_count,e_ncr_count,e_dial100_count
0,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.0,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0,0.000000,1.0,39,2,2,5,0,61,18.0,29,2,2,1,2,53,16.0
1,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.0,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0,0.000000,2.0,25,4,4,3,0,61,20.0,25,3,3,2,2,65,29.0
2,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.0,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0,0.000000,3.0,26,4,3,3,2,88,26.0,63,5,4,3,0,65,35.0
3,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.0,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0,0.000000,5.0,31,8,3,16,0,101,56.0,30,6,3,4,2,87,29.0
4,10512011,0.0,0.444444,3.666667,No,0.0,0.500000,4.0,0.001526,Female,1051201.0,female,3023.0,107000,Urban,4,-0.004295,Treatment,regular mhd,3000,7.0,3.717949,2.15,1,0,0.0,0.000000,6.0,47,7,5,5,0,97,28.0,43,12,8,18,1,111,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36229,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.0,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0,0.024804,8.0,28,1,1,0,0,39,14.0,15,4,1,0,0,19,8.0
36230,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.0,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0,0.024804,9.0,15,3,2,1,0,30,9.0,13,0,0,0,0,24,8.0
36231,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.0,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0,0.024804,10.0,22,1,1,0,0,36,16.0,26,2,2,1,1,72,11.0
36232,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.0,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0,0.024804,11.0,19,1,1,1,0,31,14.0,15,3,2,1,1,83,19.0
36233,80602481,0.0,0.666667,4.000000,No,0.0,0.333333,3.0,0.003290,Female,8060248.0,female,12180.0,77000,Rural,18,-1.210380,Treatment,regular mhd,12000,8.0,3.527859,3.08,1,0,0.0,0.024804,12.0,16,2,1,0,0,28,10.0,10,0,0,0,2,51,11.0

### Step 4.3: Merge CCTV and Police Station Personnel (Q4)

In [ ]:
#First drop duplicate columns rather than joining (for sake of simplicity)
psp_short = psp_df.drop(columns = ['urban',	'dist_urban', 'strat_pca', 'treatment', 'group', 'dist_id', 'training_score', 'regular_whd', 'women_whd'])
CCTVwFemaleStaff = pd.merge(CCTV_df, psp_short, how='left', on='ps_code')

In [ ]:
with pd.option_context('display.max_rows', 10, 'display.max_columns', None):
        display(CCTVwFemaleStaff)

,Unnamed: 0,ps_code,urban,dist_urban,strat_pca,treatment,group,dist_id,training_score,regular_whd,women_whd,dayofweek,timeofday,eavg_all,eavg_women,eavg_wprop,bavg_all,bavg_women,bavg_wprop,station_index,e_total_surveyed,e_female_surveyed,e_male_surveyed,e_total_staff,e_female_staff,e_total_officers,e_female_officers,e_male_staff,e_male_officers,e_female_sho,b_total_staff,b_female_staff,b_male_staff,b_total_officers,b_female_officers,b_male_officers,b_female_sho,e_total_sampled,e_female_sampled,e_male_sampled,b_total_sampled,b_female_sampled,b_male_sampled,b_total_surveyed,b_female_surveyed,b_male_surveyed,population,implement_quality,comm_outreach_strength,e_male_weight,b_male_weight,e_female_weight,b_female_weight
0,0,1001.0,Rural,1,-0.234041,Treatment,women officers,1000,2.916667,0,1,Thu,morning,255.564060,11.876471,0.045578,69.000000,3.000000,0.040147,0,12,1,11,48,6,11,1,42,10,0,39,3,36,10,0,10,0,12,1,11,12,1,11,10,0,10,129345,9,2.200000,3.818182,3.272727,6.000000,3.000000
1,1,1002.0,Rural,1,-0.960574,Control,control,1000,1.545454,0,0,Mon,evening,76.029686,16.920221,0.206208,67.200000,10.800000,0.193587,1,11,0,11,29,2,6,0,27,6,0,20,1,19,7,1,6,0,11,0,11,12,1,11,11,0,11,170000,7,1.798067,2.454546,1.727273,0.000000,1.000000
2,2,1003.0,Rural,1,1.042663,Control,control,1000,1.090909,0,0,Sun,morning,134.501400,2.782788,0.020138,145.156894,13.295626,0.089801,2,11,1,10,79,6,13,2,73,11,0,56,7,49,12,2,10,0,12,2,10,12,2,10,11,2,9,102467,7,1.798067,7.300000,4.900000,3.000000,3.500000
3,3,1004.0,Rural,1,-1.590761,Treatment,regular mhd,1000,3.897297,1,0,Sat,evening,114.906030,1.166559,0.009661,145.156894,13.295626,0.089801,3,10,2,8,33,3,7,1,30,6,0,22,4,18,4,1,3,0,13,3,10,13,3,10,13,3,10,54000,7,2.030000,3.000000,1.800000,1.000000,1.333333
4,4,1005.0,Rural,1,-1.570695,Treatment,women officers,1000,4.157658,0,1,Thu,morning,145.051802,14.689332,0.099037,139.306850,13.524937,0.118475,4,12,3,9,32,7,4,2,25,2,1,28,3,25,6,0,6,0,12,3,9,12,2,10,12,2,10,76376,9,2.200000,2.777778,2.500000,2.333333,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411,3411,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Wed,evening,85.364350,16.106482,0.201576,145.156894,13.295626,0.089801,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,8,3.080000,2.272727,1.909091,0.000000,0.000000
3412,3412,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Mon,evening,145.051802,14.689332,0.099037,55.612656,9.521234,0.173972,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,8,3.080000,2.272727,1.909091,0.000000,0.000000
3413,3413,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Mon,morning,145.051802,14.689332,0.099037,87.081830,6.381884,0.055709,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,8,3.080000,2.272727,1.909091,0.000000,0.000000
3414,3414,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Fri,morning,97.801315,1.657649,0.018386,65.137810,4.165790,0.070516,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,8,3.080000,2.272727,1.909091,0.000000,0.000000
3415,3415,12180.0,Rural,18,-1.210380,Treatment,regular mhd,12000,3.527859,1,0,Tue,morning,140.565430,5.967400,0.040269,68.704315,10.950302,0.154253,179,11,0,11,30,5,5,2,25,3,0,21,0,21,5,0,5,0,11,0,11,11,0,11,11,0,11,77000,8,3.080000,2.272727,1.909091,0.000000,0.000000

The columns from police survery were added on successfully!

### Step 4.4: Send to CSV!

In [ ]:
#Update Q1, Q2, Q4 and realvent data
dataQOne = {'Police_Stations':pol_and_station, 'Random':random_df}
dataQTwo = {'Citizen_Admin':citizen_and_admin, 'Random':random_df}
dataQFour = {'Random':random_df, 'Admin':admin_long_df, 'CCTVwFemaleStaff':CCTVwFemaleStaff}
relaventData = [('Question_1', dataQOne), ('Question_2', dataQTwo),('Question_3', dataQThree), ('Question_4', dataQFour)]

In [ ]:
#Remove all dups from all dataframes (just in case)
for i in relaventData:
  for key, value in i[1].items():
      value = value.drop_duplicates()

In [ ]:
#Export all data to csv!

for i in relaventData:
  for key, value in i[1].items():

    # define paths
    folderpath = f'/content/drive/MyDrive/Data - Human Centered DS/Cleaned Data/{i[0]}'
    filepath = folderpath + f'/{key}.csv'
    # print(filepath)

    # if the subfolder doesn't exist yet, make it
    if not os.path.exists(folderpath):
      os.makedirs(folderpath)

    # write to file!
    value.to_csv(filepath, index=False)